site_name: MkDocs static i18n plugin demo
site_url: https://ultrabug.github.io/mkdocs-static-i18n
repo_url: https://github.com/ultrabug/mkdocs-static-i18n

docs_dir: tests/docs_suffix_structure

theme:
  name: material
  font: false
  icon:
    logo: material/file-document-multiple
  palette:
    primary: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ultrabug/mkdocs-static-i18n
      name: mkdocs-static-i18n on Github

markdown_extensions:
  - admonition

# nav:
#   - Home: index.md
#   - Topic1: topic1/named_file.md
#   - Topic2: topic2/README.md

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "MkDocs static i18n plugin demo (en)"
        - locale: fr
          name: Français
          build: true
          site_name: "Démo du plugin MkDocs static i18n (fr)"
          theme:
            palette:
              primary: red
          nav_translations:
            Topic1: Sujet1 Traduit
            Topic2: Sujet2 Traduit
        - locale: de
          name: German
          build: true
          site_name: "Demo des plugin MkDocs static i18n (de)"
          theme:
            palette:
              primary: yellow
          nav:
            - Home: index.md
            - Das Topic 2: topic2/README.md
