site_name: MkDocs static i18n plugin demo
site_url: https://ultrabug.github.io/mkdocs-static-i18n
repo_url: https://github.com/ultrabug/mkdocs-static-i18n

plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        fr: français
